version: 0.2
phases:
  install:
    commands:
      - npm install
      - npm run test
      - npm run build
      - aws s3 sync index.html s3://karlespe-flexion-web
      - aws s3 sync dist/ s3://karlespe-flexion-web/dist
