version: 0.2
phases:
  install:
    commands:
      - npm install
      - npm run test
      - npm run build
      - aws s3 cp index.html s3://karlespe-flexion-web/
      - aws s3 cp dist/temperature.min.js s3://karlespe-flexion-web/dist/
